[package]
name = "docs-site"
description = "Cot web framework website and official guide"
authors = ["Mateusz Maćkowski <mateusz@mackowski.org>"]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
cot = { git = "https://github.com/cot-rs/cot.git", rev = "1638ac877352d22ce98d1b7f2f6e75d13fc519e8", default-features = false }
cot-site = { git = "https://github.com/cot-rs/cot-site.git", rev = "b67e46aaa6901913768ffd80a8737a79cba39db1" }
