//! List of migrations for the current app.
//!
//! Generated by cot CLI 0.1.0 on 2025-02-13 10:29:03+00:00

pub mod m_0001_initial;
pub mod m_0002_add_is_active;
/// The list of migrations for current app.
pub const MIGRATIONS: &[&::cot::db::migrations::SyncDynMigration] =
    &[&m_0001_initial::Migration, &m_0002_add_is_active::Migration];
