[workspace]
members = [
    "flareon",
    "flareon-admin",
    "flareon-auth",
    "flareon-macros",
    "flareon-orm",
    # Examples
    "examples/hello-world",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
async-trait = "0.1.80"
axum = "0.7.5"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.8", features = ["derive", "env"] }
env_logger = "0.11.3"
itertools = "0.13.0"
log = "0.4.22"
serde = "1.0.203"
slug = "0.1.5"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
