[workspace]
members = [
    "flareon",
    "flareon-admin",
    "flareon-auth",
    "flareon-cli",
    "flareon-codegen",
    "flareon-macros",
    # Examples
    "examples/hello-world",
    "examples/todo-list",
    "examples/sessions",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.89"
askama = "0.12.1"
async-stream = "0.3.6"
async-trait = "0.1.83"
axum = "0.7.7"
backtrace = "0.3.74"
bytes = "1.7.2"
cargo_toml = "0.20.5"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.19", features = ["derive", "env"] }
clap-verbosity-flag = "2.2.2"
convert_case = "0.6.0"
darling = "0.20.10"
derive_builder = "0.20.1"
derive_more = { version = "1.0.0", features = ["full"] }
env_logger = "0.11.5"
fake = { version = "2.10.0", features = ["derive", "chrono"] }
flareon = { path = "flareon" }
flareon_codegen = { path = "flareon-codegen" }
flareon_macros = { path = "flareon-macros" }
form_urlencoded = "1.2.1"
futures = "0.3.31"
futures-core = "0.3.31"
futures-util = "0.3.31"
glob = "0.3.1"
hmac = "0.13.0-pre.4"
http = "1.1.0"
http-body = "1.0.1"
http-body-util = "0.1.2"
indexmap = "2.6.0"
itertools = "0.13.0"
log = "0.4.22"
mockall = "0.13.0"
password-auth = "1.1.0-pre.1"
prettyplease = "0.2.22"
proc-macro-crate = "3.2.0"
proc-macro2 = "1.0.86"
quote = "1.0.37"
rand = "0.8.5"
regex = "1.11.0"
rustversion = "1.0.17"
sea-query = "0.32.0-rc.2"
sea-query-binder = { version = "0.7.0-rc.2", features = ["sqlx-sqlite", "with-chrono", "runtime-tokio"] }
serde = "1.0.210"
sha2 = "0.11.0-pre.4"
slug = "0.1.6"
sqlx = { version = "0.8.2", default-features = false, features = ["macros", "json", "runtime-tokio", "sqlite", "chrono"] }
subtle = "2.6.1"
syn = { version = "2.0.79", features = ["full", "extra-traits"] }
sync_wrapper = "1.0.1"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tower = "0.5.1"
tower-sessions = "0.13.0"
trybuild = { version = "1.0.99", features = ["diff"] }
