services:
  mariadb:
    image: docker.io/mariadb:11
    container_name: cot-mariadb
    environment:
      MARIADB_DATABASE: mysql
      MARIADB_USER: cot
      MARIADB_PASSWORD: cot
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: docker.io/postgres:17-alpine
    container_name: cot-postgres
    environment:
      POSTGRES_USER: cot
      POSTGRES_PASSWORD: cot
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
