[package]
name = "example-sessions"
version = "0.1.0"
publish = false
description = "Sessions - Flareon example."
edition = "2021"

[dependencies]
flareon = { path = "../../flareon" }
rinja = "0.3.5"
