[package]
name = "flareon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Modern web framework focused on speed and ease of use."

[dependencies]
askama.workspace = true
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
chrono.workspace = true
derive_builder.workspace = true
derive_more.workspace = true
flareon_macros.workspace = true
form_urlencoded.workspace = true
futures-core.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
indexmap.workspace = true
log.workspace = true
regex.workspace = true
sea-query-binder.workspace = true
sea-query.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true

[dev-dependencies]
async-stream.workspace = true
fake.workspace = true
futures.workspace = true
rand.workspace = true
