[package]
name = "flareon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Modern web framework focused on speed and ease of use."

[dependencies]
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
derive_builder.workspace = true
indexmap.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
