[package]
name = "example-todo-list"
version = "0.1.0"
publish = false
description = "TODO List - Flareon example."
edition = "2021"

[dependencies]
flareon = { path = "../../flareon" }
rinja = "0.3.5"
