//! Generated by cot CLI 0.1.0 on 2026-05-21 12:00:00+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "cot";
    const MIGRATION_NAME: &'static str = "m_0002_add_is_active";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] =
        &[::cot::db::migrations::MigrationDependency::migration(
            "cot",
            "m_0001_initial",
        )];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] =
        &[::cot::db::migrations::Operation::add_field()
            .table_name(::cot::db::Identifier::new("cot__database_user"))
            .field(
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("is_active"),
                    <bool as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<bool as ::cot::db::DatabaseField>::NULLABLE),
            )
            .build()];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _DatabaseUser {
    #[model(primary_key)]
    id: cot::db::Auto<i64>,
    #[model(unique)]
    username: crate::db::LimitedString<{ crate::auth::db::MAX_USERNAME_LENGTH }>,
    password: crate::auth::PasswordHash,
    is_active: bool,
}
