//! List of migrations for the current app.
//!
//! Generated by cot CLI 0.1.3 on 2025-03-12 13:50:59+00:00

pub mod m_0001_initial;
/// The list of migrations for current app.
pub const MIGRATIONS: &[&::cot::db::migrations::SyncDynMigration] = &[&m_0001_initial::Migration];
