//! Generated by cot CLI 0.3.1 on 2025-06-30 15:43:42+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "cot_session";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] =
        &[::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("cot__session"))
            .fields(&[
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("id"),
                    <cot::db::Auto<i32> as ::cot::db::DatabaseField>::TYPE,
                )
                .auto()
                .primary_key()
                .set_null(<cot::db::Auto<i32> as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("key"),
                    <String as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("data"),
                    <String as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
            ])
            .build()];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Session {
    #[model(primary_key)]
    pub id: cot::db::Auto<i32>,
    pub key: String,
    pub data: String,
}
