[package]
name = "flareon_codegen"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Modern web framework focused on speed and ease of use - code generation utils."

[dependencies]
convert_case.workspace = true
darling.workspace = true
syn.workspace = true
