[package]
name = "example-admin"
version = "0.1.0"
publish = false
description = "Admin panel - Flareon example."
edition = "2021"

[dependencies]
env_logger = "0.11.5"
flareon = { path = "../../flareon" }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
