[package]
name = "example-custom-error-pages"
version = "0.1.0"
publish = false
description = "Custom Error Pages - Cot example."
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
cot = { path = "../../cot" }
