[workspace]
semver_check = false
git_release_enable = false
changelog_update = false
git_release_draft = true
git_release_body = """
TODO: add changelog
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[[package]]
name = "cot"
changelog_update = false
git_release_enable = true

[[package]]
name = "cot-cli"
changelog_update = false
git_release_enable = true
