[package]
name = "example-custom-task"
version = "0.1.0"
publish = false
description = "Custom tasks - Cot example."
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
cot = { path = "../../cot" }
