name: Cargo Semver Checks

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

env:
  CARGO_TERM_COLOR: always
  CI: true
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semver-check:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    name: Semver compatibility check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache Cargo registry
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'rust-semver'
          cache-bin: 'false'

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Install cargo-semver-checks
        run: cargo install cargo-semver-checks --locked

      - name: Find latest tag
        id: get_tag
        run: |
          git fetch --tags
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Build previous release (latest tag)
        run: |
          git checkout ${{ steps.get_tag.outputs.tag }}
          cargo build --release
          git checkout ${{ github.sha }}

      - name: Run cargo-semver-checks
        run: cargo semver-checks check-release
